
LDLIBS= -lCoreFoundation -lFoundation -lPerformance

OBJECTS = \
	WebServer \
	WebServerBundles \
	WebServerConnection \
	WebServerField \
	WebServerForm \
	WebServerHeader \
	WebServerTable \

include ${MYOS_PATH}/sdk/$(BASE_OS)/makefile-shared
