
LDLIBS= -lCoreFoundation -lFoundation
#LDLIBS= -lCoreFoundation -lFoundation -lPerformance

OBJECTS = \
	WebServer.o \
	WebServerBundles.o \
	WebServerConnection.o \
	WebServerField.o \
	WebServerForm.o \
	WebServerHeader.o \
	WebServerTable.o \

include ${MYOS_PATH}/sdk/$(BASE_OS)/makefile-shared
