
LDLIBS= -lCoreFoundation -lFoundation

OBJECTS = \
        WebServices \
	GWSBinding \
	GWSCoder \
	GWSDocument \
	GWSElement \
	GWSExtensibility \
        GWSHash \
	GWSMessage \
	GWSPort \
	GWSPortType \
	GWSService \
	GWSSOAPCoder \
	GWSXMLRPCCoder \
	GWSJSONCoder \
	WSSUsernameToken \

include ${MYOS_PATH}/sdk/$(BASE_OS)/makefile-shared
