
LDLIBS= -lCoreFoundation -lFoundation

OBJECTS = \
        WebServices.o \
	GWSBinding.o \
	GWSCoder.o \
	GWSDocument.o \
	GWSElement.o \
	GWSExtensibility.o \
        GWSHash.o \
	GWSMessage.o \
	GWSPort.o \
	GWSPortType.o \
	GWSService.o \
	GWSSOAPCoder.o \
	GWSXMLRPCCoder.o \
	GWSJSONCoder.o \
	WSSUsernameToken.o \

include ${MYOS_PATH}/sdk/$(BASE_OS)/makefile-shared
